language: python

python:
  - 3.5.0
env:
  APP_ENV=Testing

services: postgresql

addons:
  postgresql: "9.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  # Suppresses all user prompts. An example prompt is asking about removing stale content types.
  # - python manage.py migrate --noinput
  # collects all static files in the application like css files
  # - python manage.py collectstatic --noinput

script:
  - python manage.py test
  - coverage run --source=. manage.py test

after_script:
  - coveralls
